name: Manual workflow for automated tests on app-staging, e2e-branch all

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm install
      - name: Test
        shell: bash
        run: node ./node_modules/mocha/bin/mocha 'tests/*.js'
